### ISSUE TITLE
used ram for each file

### ISSUE THREAD

**Issue by geologic** [pholmes2012/Simple_FRAM_FileSystem#1]
Hi

I'm using your library with a I2C MR44V100 chip (256Kb).
I created a new volume and checked space:

size: 131072 bytes
available: 131012 bytes

So i assume your library allocates 60 bytes for filesystem.
I created a structure with 9 bytes:

```
struct MyLogDataStructure {                    
  byte AA;                                       //    1 Byte year (0 -> 99)
  byte MM;                                     //    1 Byte month (1 -> 12)
  byte DD;                                      //    1 Byte day (1 -> 31)
  byte HH;                                      //    1 Byte hour (0 -> 23)
  byte MN;                                     //    1 Byte minute (0 -> 59)
  unsigned int cont1;                     //    2 Bytes counter (0 -> 65535)
  byte vcc;                                      //    1 Byte Vcc (0 -> 255)
  int8_t temp;                                 //    1 byte temperature (-127 -> 127)
}; 
```

and saved 3 files to memory, each file named "1", "2", "3":

```
MyLogDataStructure loggedData;
int nlogs;
char logfile[6];

for (byte i=0;i<3;i++) {
  nlogs=g_ffs.FileCount()+1;
  itoa(nlogs,logfile,10);
  if (g_file.fOpen(logfile)==false) {
    if (g_file.fCreate(logfile, sizeof(loggedData))) {
      g_file.fWrite(&loggedData, sizeof(loggedData));
    } else {
      Serial.print(F(" FAILED! CHECK FREE MEMORY: "));   
      Serial.println(g_ffs.VolumeFree()); 
    }
  }
}
```

After that i checked available space and got 130901 bytes, so my 3 files are using 111 bytes, or 37 bytes each.
I wrote 3 more files and got the same result, each file uses 37 bytes. 

Shouldn't each file use only 9 bytes? Why the extra 28 bytes?

**Comment by pholmes2012** [comment]
This gets saved for each file...

	uint32 m_dataOffset;
	uint32 m_dataWrittenSize;
	uint32 m_dataMaxSize;
	char m_name[SFFS_FILE_NAME_BUFFER_LEN];

Which is 28 bytes, It could be optimised down I guess but I have no plans to do this.

**Comment by geologic** [comment]
So, there's a 28 bytes overhead for each file.
I was writing several files with 9 bytes of data, better to save just one file with several lines of 9 bytes of data.

Thanks for the answer.
